# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\student_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1007, 783)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(70, 30, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.first_name_input = QtWidgets.QLineEdit(Dialog)
        self.first_name_input.setGeometry(QtCore.QRect(250, 50, 211, 41))
        self.first_name_input.setObjectName("first_name_input")
        self.last_name_input = QtWidgets.QLineEdit(Dialog)
        self.last_name_input.setGeometry(QtCore.QRect(250, 120, 211, 41))
        self.last_name_input.setObjectName("last_name_input")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(70, 100, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.class_id_input = QtWidgets.QLineEdit(Dialog)
        self.class_id_input.setGeometry(QtCore.QRect(250, 190, 211, 41))
        self.class_id_input.setObjectName("class_id_input")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(70, 170, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.add_button = QtWidgets.QPushButton(Dialog)
        self.add_button.setGeometry(QtCore.QRect(560, 20, 141, 71))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.add_button.setFont(font)
        self.add_button.setObjectName("add_button")
        self.update_button = QtWidgets.QPushButton(Dialog)
        self.update_button.setGeometry(QtCore.QRect(560, 100, 141, 71))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.update_button.setFont(font)
        self.update_button.setObjectName("update_button")
        self.delete_button = QtWidgets.QPushButton(Dialog)
        self.delete_button.setGeometry(QtCore.QRect(560, 180, 141, 71))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.delete_button.setFont(font)
        self.delete_button.setObjectName("delete_button")
        self.table_students = QtWidgets.QTableWidget(Dialog)
        self.table_students.setGeometry(QtCore.QRect(10, 270, 1007, 591))
        self.table_students.setObjectName("table_students")
        self.table_students.setColumnCount(0)
        self.table_students.setRowCount(0)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Student managment"))
        self.label.setText(_translate("Dialog", "First name"))
        self.label_2.setText(_translate("Dialog", "Last name"))
        self.label_3.setText(_translate("Dialog", "class ID"))
        self.add_button.setText(_translate("Dialog", "Add"))
        self.update_button.setText(_translate("Dialog", "Update"))
        self.delete_button.setText(_translate("Dialog", "Delete"))
